---
Name: nswdpc-oldmantium
---
NSWDPC\Utilities\Cloudflare\PurgeRecord:
  extensions:
    - 'NSWDPC\Utilities\Cloudflare\DataObjectPurgeable'
    - 'Silverstripe\Versioned\Versioned'
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - 'NSWDPC\Utilities\Cloudflare\SiteTreeExtension'
SilverStripe\Assets\File:
  extensions:
    - 'NSWDPC\Utilities\Cloudflare\FileExtension'
